[options]
; Admin password (used to manage databases)
admin_passwd = admin123

; PostgreSQL database settings
db_host = localhost
db_port = False
db_user = odoo
db_password = False

; Addons path
addons_path = /opt/odoo/addons

; Server settings
xmlrpc_port = 8069
logfile = /var/log/odoo/odoo.log
